# Classical error correction with linear codes

Information is an inherently physical object. To communicate information we must create a physical manifestation such as speech or writing. Any physical system can fail and when it does the information it carries can be lost or distorted.

Suppose Alice and Bob agree that Alice will turn the kitchen light on if she is working from home and turn it off otherwise. The idea is efficient but it depends entirely on the light functioning. If the bulb fails, Bob may draw the wrong conclusion despite Alice’s intention remaining unchanged. To reduce this risk Alice could instead turn on the kitchen, bedroom and bathroom lights. It is unlikely that all three bulbs fail at once, so Bob is far more likely to receive the intended message.

This is an example of classical error correction. Using multiple bulbs introduces redundancy into the communication channel so that even when parts of the physical system fail the original message can still be recovered. The goal of error correction is to introduce redundancy and structure into the communication channel so that the information remains intact despite physical imperfections.

## Encoding messages as binary strings

We can encode the light switch example using binary numbers. The switch is either on or off, which we encode as 
$1$ for on and $0$ for off. This is an example of a bit. A bit represents a physical system with two discrete states which we label as $0$ and $1$.

Errors can occur when a bit changes state: for example a $0$ becomes a $1$ or a $1$ becomes a $0$. These are called bit-flip errors. For example, if Alice tries to send $1$ by turning the light on but the bulb fails, Bob will interpret it as a $0$ and misinterpret the message.

A simple way to reduce errors is to increase redundancy by sending multiple copies of the same bit. We then assume that the value appearing most often is the intended message. For example, suppose that each lightbulb has probability $0.1$ of failure and Bob receives the message $101$. We know there has been an error because Alice either sends $000$ or $111$. Thus, either the middle bulb failed and Alice sent $111$ or both the first and third bulb failed and Alice sent $000$. Assuming each bulb fails independently, we can compute the probability Alice sent either message. In particular, we have that
\begin{align*}
\mathbb{P}(\text{Alice sent 111 | Bob received 101}) &= \mathbb{P}(\text{Bulb 1 did not fail}) \cdot \mathbb{P}(\text{Bulb 2 failed}) \cdot \mathbb{P}(\text{Bulb 3 did not fail}) \\ &= 0.9 \cdot 0.1 \cdot 0.9 = 0.081,
\end{align*}
and
\begin{align*}
\mathbb{P}(\text{Alice sent 000 | Bob received 101}) &= \mathbb{P}(\text{Bulb 1 failed}) \cdot \mathbb{P}(\text{Bulb 2 did not fail}) \cdot \mathbb{P}(\text{Bulb 3 failed}) \\ &= 0.1 \cdot 0.9 \cdot 0.1 = 0.009.
\end{align*}
Therefore, given that Bob received the message $101$, it is more likely that the intended message was $111$ than $000$. 

Adding more lightbulbs increases the likelihood that Bob correctly interprets the intended message. However, there is a trade-off. Sending more copies also increases the number of bits Alice must use and Bob must check, which takes more time and reduces efficiency. We can see this in the following example.

**Example.** Let us first consider what happens for a single bit transmission. We define a function `transmit_single_bit` that simulates sending a single bit over a noisy channel. The channel flips the input bit with probability p=`flip_probabilty`.

In [ ]:
import random

def send_single_bit(bit: int, flip_probability: float) -> int:
    """ 
    Transmits one bit across a binary symmetric channel.
    Each bit has probability flip_probability of being flipped.
    """
    if random.random() < flip_probability:
        return (bit + 1) % 2
    return bit

bit = 0
flip_probability = 0.2
num_transmissions = 10
for _ in range(num_transmissions):
    r = send_single_bit(bit,flip_probability)
    print(f"Sent: {bit} | Received: {r} | Correct: {bit == r}")

The received bit does not always match the sent bit because the channel introduces noise. To reduce the effect of this noise we use the idea we talked about earlier; we send multiple copies of the same bit. The `encode` function takes a bit $b$ and creates a bit string $bb \dots b$ of length `num_copies`.

In [ ]:
def encode(bit: int, num_copies: int = 1):
    """
    Create bitstring of num_copies of bit.
    """
    return [bit]*num_copies

Now we transmit this message by sending each bit across our channel.

In [ ]:
def send(message: list[int], flip_probability: float):
    return [send_single_bit(m, flip_probability) for m in message]

Finally, once we receive the message we decode the message by taking the bit value that appears most often in the transmission.

In [ ]:
def decode(bits: list[int]):
    """
    Returns 1 if the majority are 1s, otherwise 0.
    """
    return 1 if sum(bits) > len(bits)//2 else 0

Now we can do the whole process where the number of copies is $3$. The function `simulate_three_bits` simulates a simple error correction scheme where each bit is sent three times. For each trial, a random bit is chosen and encoded as a block of three identical bits. Each bit in the block is then transmitted independently through the noisy channel. The receiver applies majority decoding, taking the most common value in the received block as the estimate of the original bit.


In [ ]:
def encode_send_decode(num_copies: int, flip_probability: float, num_trials: int, verbose: bool = False) -> float:
    """
    Encode a single bit as a binary string of length num_copies.
    Send across noisy channel with probability of flip p=flip_probability.
    Decode using majority vote decoder.
    Returns the proportion of correctly decoded messages.
    """
    correct = 0

    for _ in range(num_trials):
        send_bit = random.choice([0, 1])
        send_message = encode(send_bit, num_copies)
        received_message = send(send_message, flip_probability)
        decoded_bit = decode(received_message)

        if verbose:
            print(f"Alice sent bit: {send_bit}")
            print(f"Alice sent string: {send_message}")
            print(f"Bob received string: {received_message}")
            print(f"Bob decoded bit: {decoded_bit}")
            print(f"Correct? {decoded_bit == send_bit}\n")

        if decoded_bit == send_bit:
            correct += 1

    return correct / num_trials

# Parameters
num_copies = 3
num_trials = 3
flip_probability = 0.2
block_length = 3

accuracy = encode_send_decode(num_copies, flip_probability, num_trials, verbose=True)
print(f"Percentage of correct interpretations: {accuracy:.3f}")

As the number of repeated bits increases, the probability that the message will be correctly interpreted increases.

In [ ]:
import matplotlib.pyplot as plt

flip_probability = 0.1
num_trials = 50000
num_copies = range(1, 31, 2)
success_probs = []

for n in num_copies:
    success_probs.append(encode_send_decode(n, flip_probability, num_trials))

fig, ax = plt.subplots()
title = f"Probability of correct decoding with flip probability {flip_probability} vs"
title += f"\nnumber of copies of message bit"
fig.suptitle(title, fontsize=12)

ax.plot(num_copies, success_probs)
ax.set(
    xlabel="Number of copies of the message bit",
    ylabel="Probability of correct decoding",
    )
ax.grid(visible=True)

plt.show()

The graph shows that as the number of repeated copies increases, the probability of correct decoding increases. However, the probability never reaches 1. This is because majority voting assumes that the most likely transmitted bit is the one requiring the fewest flips to produce the received message. If more than half of the bits are flipped, this assumption fails and the decoder outputs the wrong value. In particular, repeating the bit n times allows us to encode $1$ piece of information into $n$ bits and correct up to $\lfloor \frac{n}{2} \rfloor$ errors.

---

In general, we would like to be able to encode more pieces of information into fewer bits and still be able to correct errors introduced by transmission. One way to do this is to generalise the repetition idea using vector spaces and linear error correction codes.

## Error correction codes

Fix an integer $n \in \mathbb{Z}_{>0}$. The binary strings of length $n$ are precisely the vectors in the vector space $(\mathbb{Z}/2\mathbb{Z})^n$. A _(binary) linear code_ of _length_ $n$ is a vector subspace $\mathcal{C}$ of $(\mathbb{Z}/2\mathbb{Z})^n$.  An element of the code $\mathcal{C}$ is called a _codeword_. The _rank_ of a code is its dimension as a vector space over $\mathbb{Z}/2\mathbb{Z}$.

**Examples**

1. Taking strings of repeating bits defines a linear code. Let $\mathcal{C}_1 = \{(0,0,0), (1,1,1)\}$. Then $\mathcal{C}_1$ is a vector subspace of $(\mathbb{Z}/2\mathbb{Z})^3$, and hence a code. The basis of the code is $\{(1,1,1)\}$. Thus, $\mathcal{C}_1$ is a code of length $3$ and rank $1$ that contains $2$ codewords. We call this code a _repetition code_.

2. The set $$\mathcal{C}_2 = \{(0,0,0),(1,1,0),(1,0,1),(0,1,1)\}$$ also forms a subspace of $(\mathbb{Z}/2\mathbb{Z})^3$, and so is a code. One basis of $\mathcal{C}_2$ is $\{(1,1,0),(1,0,1)\}$. Thus, $\mathcal{C}_2$ is a code of length $3$ and rank $2$ that contains $4$ codewords.

3. For any subset $S$ of $(\mathbb{Z}/2\mathbb{Z})^n$ the span $$\mathcal{C}(S) = \mathrm{Span}_{\mathbb{Z}/2\mathbb{Z}}(S)$$ defines a binary code of length $n$. The rank and number of codewords of $\mathcal{C}(S)$ depends on the linear relations between the elements of $S$.

Since a code is a vector subspace, it is determined by its basis. A _generator matrix_ of a code is a matrix whose rows form a basis of the code. Note that a basis of a vector space is not unique and hence the generator matrix of a code is not unique either.

**Examples.**

1. One generator matrix for $\mathcal{C}_1$ is
$$ \begin{pmatrix} 1 & 1 & 1 \end{pmatrix}. $$

2. One generator matrix for $\mathcal{C}_2$ is
$$ \begin{pmatrix} 1 & 1 & 0 \\ 1 & 0 & 1 \end{pmatrix}. $$

---

In [ ]:
import random

from linearcodes import LinearCode

# C1 = {000,111}

M1 = LinearCode([[0,0,0],[1,1,1]])
print(f"\nC1 has codewords: {M1.codewords};")
print(f"  Length: {M1.length};")
print(f"  Rank: {M1.rank};")
G1 = M1.generator_matrix
print(f"  Generator matrix: \n{G1.array}.")

# C2 = {000,110,101,011}

M2 = LinearCode([[0,0,0],[1,1,0],[1,0,1],[0,1,1]])
print(f"\nC2 has codewords: {M2.codewords};")
print(f"  Length: {M2.length};")
print(f"  Rank: {M2.rank};")
G2 = M2.generator_matrix
print(f"  Generator matrix: \n{G2.array}.")

# A random code C3

def random_code(num_generators: int, code_length: int) -> LinearCode:
    """
    Creates a random list of generator vectors of length 'code_length'
    and returns the LinearCode generated by them.
    Note that this does not necessarily create a basis of the code.
    So, the number of generators may not equal the rank of the code.
    """
    generators = []
    for _ in range(num_generators):
        generator = []
        for _ in range(code_length):
            generator.append(random.choice([0,1]))
        generators.append(generator)
    return LinearCode(generators)

M3 = random_code(3,5)
codewords = M3.codewords
print(f"\nC3 has {len(codewords)} codewords:")
print(f"  {codewords};")
print(f"  Length: {M3.length};")
print(f"  Rank: {M3.rank};")
G3 = M3.generator_matrix
print(f"  Generator matrix: \n{G3.array}.")


### Encoding messages

Previously we encoded a single bit by repeating it several times to introduce redundancy, allowing us to detect and correct errors in transmission. This can be expressed using the language of repetition codes. For instance, in a repetition code of length 3, the message 1 is encoded as 111. The generator matrix for this code is
$$ G = \begin{pmatrix} 1 & 1 & 1 \end{pmatrix}, $$
and encoding can be written as
$$ \begin{pmatrix} 1 \end{pmatrix} G = \begin{pmatrix} 1 & 1 & 1 \end{pmatrix}. $$

More general linear codes allow us to encode messages with more than one bit as codewords in a similar way using a generator matrix. Fix a linear code $\mathcal{C}$ of length $n$ and rank $k$. Right multiplication by the generator matrix $G$ of $\mathcal{C}$ defines a linear map
\begin{align*}
G \colon (\mathbb{Z}/\mathbb{2Z})^k &\to \mathcal{C}
\\
v &\mapsto vG.
\end{align*}
Therefore, we can encode any message $m \in (\mathbb{Z}/\mathbb{2Z})^k$ as the codeword $c=mG$. The _message space_ of a code $\mathcal{C}$ is the set of allowed messages in $(\mathbb{Z}/\mathbb{2Z})^k$.

### Dual codes

Fix a linear code $\mathcal{C}$ of length $n$ and rank $k$. Then its generator matrix $G$ is a $k \times n$ matrix, and left multiplication by $G$ defines a linear map
\begin{align*}
    G \colon (\mathbb{Z}/2\mathbb{Z})^n &\to (\mathbb{Z}/2\mathbb{Z})^k
    \\
    u &\mapsto Gu.
\end{align*}
The kernel of this map $\ker(G)$ is a vector subspace of $(\mathbb{Z}/2\mathbb{Z})^n$ and therefore forms another code of the same length. We call $\ker(G)$ the _dual code_ of $\mathcal{C}$ and denote it by $\mathcal{C}^{\perp}$.

There is an equivalent characterisation of the dual code:
$$\mathcal{C}^{\perp} = \{ u \in (\mathbb{Z}/2\mathbb{Z})^n \mid c \cdot u = 0 \text{ for all } c \in \mathcal{C} \}.$$
These definitions agree because a vector $u$ satisfies $Gu = 0$ exactly when it is orthogonal to every row of the generator matrix, and these rows form a basis for $\mathcal{C}$. By the Rank Nullity Theorem, since $\mathcal{C}$ has length $n$ and rank $k$, it follows that $\mathcal{C}^{\perp}$ has rank $n-k$. A generator matrix for $\mathcal{C}^\perp$ is called a _parity check matrix_ of $\mathcal{C}$, and is usually denoted by $H$.

In summary we have:
| Code $\mathcal{C}$ | Dual code $\mathcal{C}^\perp$ |
| ---               | ---                           |
| Generator matrix $G$ | Generator matrix $H$ |
| Parity check matrix $H$ | Parity check matrix $G$ |

**Example.**

The repetition code with $n=3$ has generator matrix $$ G_1 = \begin{pmatrix} 1 & 1 & 1 \end{pmatrix}.$$ Thus, the dual code is spanned by vectors $$u = \begin{pmatrix} u_1 & u_2 & u_3 \end{pmatrix} $$ such that $$ u_1 + u_2 + u_3 = 0.$$ Therefore, if $u$ is non-trivial, then it must have exactly two non-zero entries. In particular, the dual code $\mathcal{C}^\perp$ has codewords $$ \begin{pmatrix} 0 & 0 & 0 \end{pmatrix}, \; \begin{pmatrix} 1 & 1 & 0 \end{pmatrix}, \; \begin{pmatrix} 1 & 0 & 1 \end{pmatrix}, \; \begin{pmatrix} 0 & 1 & 1 \end{pmatrix}. $$ Thus, a generator matrix for $\mathcal{C}^\perp$, and hence a parity check matrix for $\mathcal{C}$, is given by $$H = \begin{pmatrix} 1 & 1 & 0 \\ 1 & 0 & 1 \end{pmatrix}.$$



In [ ]:
import random

from linearcodes import LinearCode

# C1 = {000,111}

M1 = LinearCode([[0,0,0],[1,1,1]])
print(f"\nC1 has codewords: {M1.codewords};")
print(f"  Length: {M1.length};")
print(f"  Rank: {M1.rank};")
G1 = M1.generator_matrix
print(f"  Generator matrix: \n{G1.array}.")
H1 = M1.parity_check_matrix
print(f"  Parity check matrix: \n{H1.array}")

# C2 = {000,110,101,011}

M2 = LinearCode([[0,0,0],[1,1,0],[1,0,1],[0,1,1]])
print(f"\nC2 has codewords: {M2.codewords};")
print(f"  Length: {M2.length};")
print(f"  Rank: {M2.rank};")
G2 = M2.generator_matrix
print(f"  Generator matrix: \n{G2.array}.")
H2 = M2.parity_check_matrix
print(f"  Parity check matrix: \n{H2.array}")

# A random code C3

M3 = random_code(3,5)
codewords = M3.codewords
print(f"\nC3 has {len(codewords)} codewords:")
print(f"  {codewords};")
print(f"  Length: {M3.length};")
print(f"  Rank: {M3.rank};")
G3 = M3.generator_matrix
print(f"  Generator matrix: \n{G3.array}.")
H3 = M3.parity_check_matrix
print(f"  Parity check matrix: \n{H3.array}")


### Parity check equations

The generator matrix of the dual code $\mathcal C^{\perp}$ of a code $\mathcal{C}$ is called the _parity check matrix_ of $\mathcal{C}$ and is denoted by $H$. The parity check matrix is useful to determine vectors that are codewords of $\mathcal{C}$. Since each of the rows of $H$ is a codeword in the dual code $\mathcal{C}^\perp$, its dot product with a codeword of $\mathcal{C}$ is trivial. Thus, a vector $v \in (\mathbb Z/2\mathbb Z)^n$ lies in the code $\mathcal C$ if and only if $$H v^{\mathrm T} = 0.$$
Each row of $H$ is a vector of $0$'s and $1$'s. Therefore, each row defines an equation that adds up a subset of the coordinates of $v$ which we call a _parity check equation_. 

---
**Example.** Consider the repetition code of length three with generator matrix
$$G = \begin{pmatrix} 1 & 1 & 1 \end{pmatrix}.$$
A parity check matrix for this code is
$$H = \begin{pmatrix} 1 & 1 & 0 \\ 1 & 0 & 1 \end{pmatrix}.$$
Since the parity check matrix has two rows, there are two parity check equations. In particular, for a vector $$v = \begin{pmatrix} v_1 & v_2 & v_3 \end{pmatrix}$$ we have that
$$ Hv^T = \begin{pmatrix} v_1 + v_2 \\ v_2 + v_3 \end{pmatrix},$$
and the two parity check equations are
$$P_1(v) = v_1 + v_2 \; \text{ and } \; P_2(v) = v_2 + v_3.$$
The vector $v$ is a codeword exactly when $Hv^T$ is trivial, or equivalently the sums defined by $P_1$ and $P_2$ have even parity.

---

In [ ]:
def nice_print_parity_checks(code: LinearCode) -> list[str]:
    """
    Returns the parity check equations for the code as strings.
    """
    parity_check_eqns = code.parity_checks
    nice_print = []
    for pc_idx, pc_eqn in enumerate(parity_check_eqns.values(), start=1):
        terms = [f"v{bit_idx+1}" for bit_idx, bit in enumerate(pc_eqn) if bit == 1]
        readable_eqn = " + ".join(terms) if terms else "0"
        nice_print.append(f" * P{pc_idx}(v) = {readable_eqn}.")
    return nice_print

code = random_code(3, 7)
print(f"C is a code with generator matrix:\n{code.generator_matrix.array}")
nice_print = nice_print_parity_checks(code)
print(f"\nC has {len(nice_print)} parity check equations given by:")
for pc in nice_print:
    print(pc)

#### Tanner graphs

The parity check equations can be visualised as a graph via _Tanner graphs_. A Tanner graph is a bipartite graph associated with a parity check matrix. It has two types of vertices:
1. "Bit vertices"
2. "Check vertices"

The bit vertices correspond to bit indices in a codeword, so for a code of length $n$ there are $n$ bit vectices. The check vertices correspond to parity check equations, so for a code of length $n$ and rank $k$, there are $n-k$ check vertices. A bit vertex $b$ is connected to a check vertex $c$ when the bit corresponding to bit vertex $b$ appears in the parity check equation corresponding to the check vertex $c$. Tanner graphs visualise the structure of a code and are used in iterative decoding algorithms.

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
from linearcodes import LinearCode

def tanner_graph(code: LinearCode) -> nx.Graph:
    code_length = code.length
    parity_check_eqs = code.parity_checks
    num_parity_checks = code.num_parity_checks
    G = nx.Graph()
    bit_nodes = [f"v{bit_idx+1}" for bit_idx in range(code_length)]
    check_nodes = [f"P{pc_idx+1}" for pc_idx in range(num_parity_checks)]
    G.add_nodes_from(bit_nodes, bipartite=0)
    G.add_nodes_from(check_nodes, bipartite=1)
    for pc_idx, pc_eqn in enumerate(parity_check_eqs.values()):
        for bit_idx, bit in enumerate(pc_eqn):
            if bit == 1:
                G.add_edge(f"v{bit_idx+1}", f"P{pc_idx+1}")
    return G

def draw_tanner_graph(code: LinearCode, title: str = "Tanner Graph", bits_colour: str = "skyblue", pc_colour: str = "lightgreen"):
    G = tanner_graph(code)
    bit_nodes = [n for n, d in G.nodes(data=True) if d['bipartite'] == 0]
    pc_nodes = [n for n, d in G.nodes(data=True) if d['bipartite'] == 1]

    m = max(len(bit_nodes), len(pc_nodes))
    bit_prop = (m-1)/(len(bit_nodes)-1)
    pc_prop = (m-1)/(len(pc_nodes)-1)
    
    pos = {}
    for idx, node in enumerate(bit_nodes):
        pos[node] = (0, idx*bit_prop)
    for idx, node in enumerate(pc_nodes):
        pos[node] = (1, idx*pc_prop)
        
    nx.draw(G, pos, with_labels=True, node_color=[bits_colour if G.nodes[n]['bipartite'] == 0 else pc_colour for n in G.nodes()])
    plt.title(title)
    plt.show()

code = random_code(4,9)
print_pc = nice_print_parity_checks(code)
nice_print = nice_print_parity_checks(code)
print(f"\nC has {len(nice_print)} parity check equations given by:")
for pc in nice_print:
    print(pc)
draw_tanner_graph(code)


#### Syndromes.

The parity check equations can be used to detect errors. Recall that an error is a bit-flip: either $0$ becomes $1$ or $1$ becomes $0$. In $(\mathbb{Z}/2\mathbb{Z})$, this is equivalent to adding $1$. Therefore, an error can be represented by an error vector $e$, with a $1$ in each position where a bit flip occurred.

**Example.** The repetition code of length $3$ has a parity check matrix $$H = \begin{pmatrix} 1 & 1 & 0 \\ 1 & 0 & 1 \end{pmatrix}.$$
Since the length of the code is $3$, there are three possible bit-flips. Each bit flip has a unique representation as an error vector and moreover a unique syndrome.
| Error | Error vector $e$ | Syndrome $He^\mathrm{T}$ |
| ---   | ---              | ---                      |
| First bit flips | 100 | 11 |
| Second bit flips | 010 | 10 |
| Third bit flips | 001 | 01 |

As each single bit flip has a unique syndrome, assuming at most one error allows us to identify exactly which bit was flipped using the syndrome table above. However, when more than one error occurs, the syndrome is no longer unique. For example, if two bit flips occur in a 3 bit block, we obtain the following error patterns and syndromes:
| Error | Error vector $e$ | Syndrome $He^\mathrm{T}$ |
| ---   | ---              | ---                      |
| Second and third bit flip | 011 | 11 |
| First and third bit flip | 101 | 10 |
| First and second bit flip | 110 | 01 |


These syndromes coincide with those produced by single bit errors. Therefore, we cannot distinguish between single and multiple errors using the syndrome alone. However, we can still detect that an error occured because the syndrome is non-zero.

---

We have seen that syndromes do not always uniquely determine the errors that occur. However, there is a class of codes where like in the repetition code of length $3$ each _single_ bit error can be uniquely identified by its syndrome. That is, Hamming codes.

### Hamming codes

Let $\mathcal{C}$ be a linear code with parity check matrix $H$. A single bit flip in position $i$ corresponds to the error vector $e_i$ with $1$ in position $i$ and $0$ everywhere else. Then the syndrome $He_i^T$ is the $i^{th}$ column of $H$. Thus, the syndrome uniquely identifies single bit errors if and only if all columns of $H$ are distinct. Hamming codes achieve the maximum for this condition; their parity check matrices contain every non zero binary column of a fixed length. In particular, if $H$ has rank $r$, then the columns of $H$ are the binary expansions of the integers from $1$ to $2^r-1$.

**Example.** Fix $r=2$. The Hamming code of length $2^2-1 = 3$ has parity check matrix
$$ H = 
\begin{pmatrix}
1 & 0 & 1 \\
0 & 1 & 1
\end{pmatrix}. $$
Notice this is also the parity check matrix for the repetition code of length $3$. Thus, we already know that this code has rank $k=1$.

Fix $r=3$. The Hamming code of length $2^3-1 = 7$ has parity check matrix
$$ H = 
\begin{pmatrix}
1 & 0 & 1 & 0 & 1 & 0 & 1 \\
0 & 1 & 1 & 0 & 0 & 1 & 1 \\
0 & 0 & 0 & 1 & 1 & 1 & 1
\end{pmatrix}. $$
The parity check matrix is full rank because there are three columns that consist of only one $1$. Therefore, the dual code is of rank $3$ and the Hamming code is of rank $7-3=4$.

---

We can construct Hamming codes by defining their parity check matrix using binary expansions. Each column corresponds to the binary representation of an integer. The function `extend_binary_expansion` takes an integer and returns its binary expansion padded with leading zeros so that it has a fixed length.

In [ ]:
def extend_binary_expansion(n: int, length: int):
    """
    Add leading zeros before binary expansion of n.
    Create expansion of specified length.
    """
    b = bin(n)[2:]
    z = "0" * (length - len(b))
    return z + b

print(f"11 has binary expansion {bin(11)[2:]}.")
print(f"Extended to a vector of length 6: {extend_binary_expansion(11, 6)}")

The number of parity check equations fixes the number of rows in the parity check matrix, and hence the length of each column. Therefore, the number of parity checks uniquely determines a Hamming code. The function `hamming_code` takes the number of parity checks $r$ and forms the matrix whose columns are the extended binary expansions of the integers from $1$ to $2^r-1$.

In [5]:
import numpy as np
from linearcodes import LinearCode

def hamming_code(num_parity_checks: int):
    code_length = 2**(num_parity_checks)-1
    parity_check_cols = []
    for x in range(1, code_length+1):
        b = extend_binary_expansion(x, code_length)
        parity_check_cols.append(list([int(s) for s in b]))
    parity_check_matrix = np.array(parity_check_cols).T
    return LinearCode(parity_checks=parity_check_matrix.tolist())

for r in range(1,5):
    h = hamming_code(r)
    if r == 1:
        print(f"\nHamming code with {r} parity check: \n{h.parity_check_matrix}")
    else:
        print(f"\nHamming code with {r} parity checks: \n{h.parity_check_matrix}")


Hamming code with 1 parity check: 
[[1]]

Hamming code with 2 parity checks: 
[[1 0 1]
 [0 1 1]]

Hamming code with 3 parity checks: 
[[1 0 1 0 1 0 1]
 [0 1 1 0 0 1 1]
 [0 0 0 1 1 1 1]]

Hamming code with 4 parity checks: 
[[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]


The syndromes for a single bit error at index $i$ in a Hamming code picks out column $i$ in the parity check matrix, namely the reversed binary expansion of $i+1$.

In [ ]:
def compute_syndrome_error_bit(hamming_code: LinearCode, error_idx: int):
    error = [0]*hamming_code.length
    error[error_idx] = 1
    return hamming_code.syndrome(error)

def reversed_binary_to_int(binary_str: str):
    rev = ''.join(reversed(binary_str))
    return int(rev, 2)

h = hamming_code(3)
for error_idx in range(h.length):
    syndrome = compute_syndrome_error_bit(h,error_idx)
    bin_expansion = extend_binary_expansion(error_idx+1, h.num_parity_checks)
    bin_int = reversed_binary_to_int(bin_expansion)
    print(f"Bit flip index: {error_idx} || Error syndrome: {syndrome} || Binary expansion: {bin_expansion} || Integer: {bin_int}.")

However, the syndrome in a Hamming code cannot distinguish between a single bit error and some multiple bit errors. Different error patterns can produce the same syndrome meaning we cannot decide how many errors occured. We compute the syndromes for random error patterns.

In [11]:
import random

h = hamming_code(3)
for _ in range(5):
    error_vector = [random.choice([0,1]) for _ in range(h.length)]
    syndrome = h.syndrome(error_vector)
    error_bit = sum([val*2**idx for idx, val in enumerate(syndrome)])
    if error_bit != 0:
        print(f"\nError vector: {error_vector}. Syndrome: {syndrome}. Single bit error index {error_bit-1}.")
    else:
        print(f"\nError vector: {error_vector}. Syndrome: {syndrome}. Error vector is codeword.")




Error vector: [1, 1, 0, 1, 0, 0, 1]. Syndrome: [0, 0, 0]. Error vector is codeword.

Error vector: [0, 0, 0, 0, 1, 1, 1]. Syndrome: [0, 0, 1]. Single bit error index 3.

Error vector: [1, 1, 0, 1, 0, 1, 1]. Syndrome: [0, 1, 1]. Single bit error index 5.

Error vector: [1, 1, 0, 0, 0, 1, 0]. Syndrome: [1, 0, 1]. Single bit error index 4.

Error vector: [0, 0, 0, 1, 0, 1, 1]. Syndrome: [1, 0, 1]. Single bit error index 4.


### LDPC codes

An LDPC code is a linear code whose parity check matrix is sparse, meaning each parity check equation involves only a few variables. This sparsity makes it efficient to check whether a codeword contains an error. The parity checks can be visualised using a Tanner graph, a bipartite graph in which one set of nodes represents the bits in a codeword and the other set represents the parity check equations. A bit node is connected to a check node if that bit appears in the corresponding parity check equation.

To define an LDPC code, one specifies the code length (number of bits), the number of parity check equations, and the weight of each parity check (the number of bits involved in the equation).

In [ ]:
from linearcodes import RandomLDPC

ldpc_code = RandomLDPC(num_bits=9, num_parity_checks=3, parity_check_weights=[3])
ldpc_generator = ldpc_code.generator_matrix.array
print(f"LDPC code with generator matrix: \n{ldpc_generator}")
print_parity_checks(ldpc_code)
draw_tanner_graph(ldpc_code)